In [36]:
import pandas as pd

df = pd.read_csv("../data/Sample - Superstore.csv", encoding="latin-1")

print(df.shape)
df.head()

(9994, 21)

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,1,CA-2016-152156,11/8/2016,11/11/2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600,2,0.00,41.9136
1,2,CA-2016-152156,11/8/2016,11/11/2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3,0.00,219.5820
2,3,CA-2016-138688,6/12/2016,6/16/2016,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,90036,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200,2,0.00,6.8714
3,4,US-2015-108966,10/11/2015,10/18/2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5,0.45,-383.0310
4,5,US-2015-108966,10/11/2015,10/18/2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680,2,0.20,2.5164

In [37]:
print("Lignes :", len(df))
print("Commandes uniques :", df["Order ID"].nunique())
print("Clients uniques :", df["Customer ID"].nunique())
print("Produits uniques :", df["Product ID"].nunique())

Lignes : 9994
Commandes uniques : 5009
Clients uniques : 793
Produits uniques : 1862

In [38]:
# 1. valeurs manquantes par colonne
valeur=df.isna().sum()
print("Valeur:", valeur)

doublons_reels = df.drop(columns="Row ID").duplicated().sum()
print("Doublons réels :", doublons_reels)

Valeur: Row ID           0
Order ID         0
Order Date       0
Ship Date        0
Ship Mode        0
Customer ID      0
Customer Name    0
Segment          0
Country          0
City             0
State            0
Postal Code      0
Region           0
Product ID       0
Category         0
Sub-Category     0
Product Name     0
Sales            0
Quantity         0
Discount         0
Profit           0
dtype: int64
Doublons réels : 1

In [39]:
df_original = pd.read_csv("../data/Sample - Superstore.csv", encoding="latin-1")
df_original[df_original.drop(columns="Row ID").duplicated(keep=False)]

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
3405,3406,US-2014-150119,4/23/2014,4/27/2014,Standard Class,LB-16795,Laurel Beltran,Home Office,United States,Columbus,...,43229,East,FUR-CH-10002965,Furniture,Chairs,Global Leather Highback Executive Chair with P...,281.372,2,0.3,-12.0588
3406,3407,US-2014-150119,4/23/2014,4/27/2014,Standard Class,LB-16795,Laurel Beltran,Home Office,United States,Columbus,...,43229,East,FUR-CH-10002965,Furniture,Chairs,Global Leather Highback Executive Chair with P...,281.372,2,0.3,-12.0588

In [40]:
pertes = df[df["Profit"] < 0]
pertes.head()

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
3,4,US-2015-108966,10/11/2015,10/18/2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5,0.45,-383.0310
14,15,US-2015-118983,11/22/2015,11/26/2015,Standard Class,HP-14815,Harold Pawlan,Home Office,United States,Fort Worth,...,76106,Central,OFF-AP-10002311,Office Supplies,Appliances,Holmes Replacement Filter for HEPA Air Cleaner...,68.8100,5,0.80,-123.8580
15,16,US-2015-118983,11/22/2015,11/26/2015,Standard Class,HP-14815,Harold Pawlan,Home Office,United States,Fort Worth,...,76106,Central,OFF-BI-10000756,Office Supplies,Binders,Storex DuraTech Recycled Plastic Frosted Binders,2.5440,3,0.80,-3.8160
23,24,US-2017-156909,7/16/2017,7/18/2017,Second Class,SF-20065,Sandra Flanagan,Consumer,United States,Philadelphia,...,19140,East,FUR-CH-10002774,Furniture,Chairs,"Global Deluxe Stacking Chair, Gray",71.3720,2,0.30,-1.0196
27,28,US-2015-150630,9/17/2015,9/21/2015,Standard Class,TB-21520,Tracy Blumstein,Consumer,United States,Philadelphia,...,19140,East,FUR-BO-10004834,Furniture,Bookcases,"Riverside Palais Royal Lawyers Bookcase, Royal...",3083.4300,7,0.50,-1665.0522

In [41]:
nb_negatif = len(pertes)
nb_negatif

1871

In [42]:
pourcentage = nb_negatif / len(df) * 100
pourcentage

18.721232739643785

In [43]:
perte_totale = pertes["Profit"].sum()
perte_totale

np.float64(-156131.2857)

In [44]:
df[["Sales", "Quantity", "Discount", "Profit"]].describe()

              Sales     Quantity     Discount       Profit
count   9994.000000  9994.000000  9994.000000  9994.000000
mean     229.858001     3.789574     0.156203    28.656896
std      623.245101     2.225110     0.206452   234.260108
min        0.444000     1.000000     0.000000 -6599.978000
25%       17.280000     2.000000     0.000000     1.728750
50%       54.490000     3.000000     0.200000     8.666500
75%      209.940000     5.000000     0.200000    29.364000
max    22638.480000    14.000000     0.800000  8399.976000

In [46]:
print("Avant :", len(df))

df_nettoye = df.drop_duplicates(subset=df.columns.drop("Row ID"))

print("Après :", len(df_nettoye))
print("Lignes supprimées :", len(df) - len(df_nettoye))

Avant : 9994
Après : 9993
Lignes supprimées : 1

In [48]:
# 1. AVANT : vérifier le type
print("Avant :", df_nettoye["Order Date"].dtype)

# 2. CONVERTIR le texte en date
df_nettoye["Order Date"] = pd.to_datetime(df_nettoye["Order Date"], format="%m/%d/%Y")
df_nettoye["Ship Date"] = pd.to_datetime(df_nettoye["Ship Date"], format="%m/%d/%Y")

# 3. APRÈS : vérifier que ça a marché
print("Après :", df_nettoye["Order Date"].dtype)
print("Après :", df_nettoye["Ship Date"].dtype)

Avant : str
Après : datetime64[us]
Après : datetime64[us]

In [49]:
df_nettoye["Annee"] = df_nettoye["Order Date"].dt.year
df_nettoye["Mois"] = df_nettoye["Order Date"].dt.month
df_nettoye["Delai_livraison"] = (df_nettoye["Ship Date"] - df_nettoye["Order Date"]).dt.days

df_nettoye[["Order Date", "Ship Date", "Annee", "Mois", "Delai_livraison"]].head()

  Order Date  Ship Date  Annee  Mois  Delai_livraison
0 2016-11-08 2016-11-11   2016    11                3
1 2016-11-08 2016-11-11   2016    11                3
2 2016-06-12 2016-06-16   2016     6                4
3 2015-10-11 2015-10-18   2015    10                7
4 2015-10-11 2015-10-18   2015    10                7

In [56]:
df_nettoye["Delai_livraison"] = (df_nettoye["Ship Date"] - df_nettoye["Order Date"]).dt.days

In [ ]:
#Bonus : et si on regardait le délai moyen par mode de livraison
df_nettoye.groupby("Ship Mode")["Delai_livraison"].mean()

Ship Mode
First Class       2.182705
Same Day          0.044199
Second Class      3.238046
Standard Class    5.006704
Name: Delai_livraison, dtype: float64

In [60]:
df_nettoye["Marge"] = df_nettoye["Profit"] /df_nettoye["Sales"]* 100
pourcentage
df_nettoye[["Sales", "Profit", "Marge"]].head()

      Sales    Profit  Marge
0  261.9600   41.9136  16.00
1  731.9400  219.5820  30.00
2   14.6200    6.8714  47.00
3  957.5775 -383.0310 -40.00
4   22.3680    2.5164  11.25

In [61]:
df_nettoye.groupby("Category")["Marge"].mean().round(1).sort_values()

Category
Furniture           3.9
Office Supplies    13.8
Technology         15.6
Name: Marge, dtype: float64

In [62]:
df_nettoye.to_csv("../data/superstore_clean.csv", index=False)
print("Fichier exporté :", len(df_nettoye), "lignes,", len(df_nettoye.columns), "colonnes")

Fichier exporté : 9993 lignes, 25 colonnes

In [63]:
df_nettoye.to_excel("../data/superstore_clean.xlsx", index=False, sheet_name="Ventes")
print("Export Excel terminé ✅")

Export Excel terminé ✅